apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anvil-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/terencetatefua/anvilops-infra
    targetRevision: main
    path: gitops/charts/anvil-app
    helm:
      releaseName: anvil-app-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: anvil
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
